export const books = [
  { 
    id: 1, 
    title: 'Laskar Pelangi', 
    author: 'Andrea Hirata', 
    price: 89000, 
    originalPrice: 125000,
    category: 'Novel', 
    tags: ['Novel', 'Inspiratif', 'Pendidikan'],
    image: 'https://placehold.co/400x600/E8F5E9/2E7D32?text=Laskar+Pelangi',
    description: 'Novel legendaris karya Andrea Hirata yang menceritakan perjuangan anak-anak Belitung dalam meraih pendidikan dengan penuh semangat dan optimisme.',
    rating: 4.8,
    reviews: 1024,
    discount: 30
  },
  { 
    id: 2, 
    title: 'Dilan: Dia adalah Dilanku Tahun 1990', 
    author: 'Pidi Baiq', 
    price: 75000, 
    originalPrice: 95000,
    category: 'Romance', 
    tags: ['Novel', 'Romantis', 'Fiksi'],
    image: 'https://placehold.co/400x600/FCE4EC/C2185B?text=Dilan+1990',
    description: 'Kisah cinta remaja yang ringan, ikonik, dan sangat populer di Indonesia. Dilan dengan gaya romantisnya yang unik berhasil mencuri perhatian Milea.',
    rating: 4.7,
    reviews: 890,
    discount: 20
  },
  { 
    id: 3, 
    title: 'Filosofi Teras', 
    author: 'Henry Manampiring', 
    price: 92000, 
    originalPrice: 115000,
    category: 'Self-Development', 
    tags: ['Non-Fiksi', 'Filosofi', 'Development'],
    image: 'https://placehold.co/400x600/E3F2FD/1976D2?text=Filosofi+Teras',
    description: 'Buku non-fiksi bestseller yang memperkenalkan stoikisme dengan bahasa sederhana dan relevan untuk kehidupan modern.',
    rating: 4.9,
    reviews: 1560,
    discount: 20
  },
  { 
    id: 4, 
    title: 'Bumi Manusia', 
    author: 'Pramoedya Ananta Toer', 
    price: 105000, 
    originalPrice: 150000,
    category: 'Sejarah', 
    tags: ['Novel', 'Sejarah', 'Klasik'],
    image: 'https://placehold.co/400x600/FFF3E0/F57C00?text=Bumi+Manusia',
    description: 'Novel klasik Indonesia yang mengisahkan kehidupan di masa kolonial Belanda dengan sangat mendalam dan menyentuh.',
    rating: 4.9,
    reviews: 2140,
    discount: 30
  },
  { 
    id: 5, 
    title: 'Cantik Itu Luka', 
    author: 'Eka Kurniawan', 
    price: 98000, 
    originalPrice: 130000,
    category: 'Fiksi', 
    tags: ['Novel', 'Fiksi', 'Magis'],
    image: 'https://placehold.co/400x600/F3E5F5/7B1FA2?text=Cantik+Itu+Luka',
    rating: 4.6,
    reviews: 780,
    discount: 25
  },
  { 
    id: 6, 
    title: 'Pulang', 
    author: 'Leila S. Chudori', 
    price: 88000, 
    originalPrice: 110000,
    category: 'Drama', 
    tags: ['Novel', 'Sejarah', 'Drama'],
    image: 'https://placehold.co/400x600/E0F2F1/00796B?text=Pulang',
    rating: 4.7,
    reviews: 650,
    discount: 20
  },
  { 
    id: 7, 
    title: 'Negeri 5 Menara', 
    author: 'Ahmad Fuadi', 
    price: 79000, 
    originalPrice: 99000,
    category: 'Inspiratif', 
    tags: ['Novel', 'Inspiratif', 'Pendidikan'],
    image: 'https://placehold.co/400x600/FFF9C4/F9A825?text=Negeri+5+Menara',
    rating: 4.8,
    reviews: 1320,
    discount: 20
  },
  { 
    id: 8, 
    title: 'Pergi', 
    author: 'Tere Liye', 
    price: 72000, 
    originalPrice: 90000,
    category: 'Petualangan', 
    tags: ['Novel', 'Petualangan', 'Inspiratif'],
    image: 'https://placehold.co/400x600/E8EAF6/3F51B5?text=Pergi',
    rating: 4.5,
    reviews: 890,
    discount: 20
  },
  { 
    id: 9, 
    title: 'Hujan', 
    author: 'Tere Liye', 
    price: 75000, 
    originalPrice: 95000,
    category: 'Fiksi', 
    tags: ['Novel', 'Drama', 'Fantasi'],
    image: 'https://placehold.co/400x600/E1F5FE/0277BD?text=Hujan',
    rating: 4.6,
    reviews: 1100,
    discount: 20
  },
  { 
    id: 10, 
    title: 'Ronggeng Dukuh Paruk', 
    author: 'Ahmad Tohari', 
    price: 95000, 
    originalPrice: 125000,
    category: 'Klasik', 
    tags: ['Novel', 'Budaya', 'Klasik'],
    image: 'https://placehold.co/400x600/FCE4EC/D81B60?text=Ronggeng',
    rating: 4.7,
    reviews: 540,
    discount: 24
  },
  { 
    id: 11, 
    title: 'Jejak Langkah', 
    author: 'Pramoedya Ananta Toer', 
    price: 102000, 
    originalPrice: 145000,
    category: 'Sejarah', 
    tags: ['Novel', 'Sejarah', 'Klasik'],
    image: 'https://placehold.co/400x600/EFEBE9/5D4037?text=Jejak+Langkah',
    rating: 4.8,
    reviews: 890,
    discount: 30
  },
  { 
    id: 12, 
    title: 'Saman', 
    author: 'Ayu Utami', 
    price: 85000, 
    originalPrice: 110000,
    category: 'Kontemporer', 
    tags: ['Novel', 'Kontemporer', 'Drama'],
    image: 'https://placehold.co/400x600/F1F8E9/689F38?text=Saman',
    rating: 4.5,
    reviews: 560,
    discount: 23
  },
  { 
    id: 13, 
    title: 'Seperti Dendam, Rindu Harus Dibayar Tuntas', 
    author: 'Eka Kurniawan', 
    price: 92000, 
    originalPrice: 120000,
    category: 'Fiksi', 
    tags: ['Novel', 'Thriller', 'Drama'],
    image: 'https://placehold.co/400x600/FBE9E7/D84315?text=Seperti+Dendam',
    rating: 4.7,
    reviews: 670,
    discount: 23
  },
  { 
    id: 14, 
    title: 'Gadis Kretek', 
    author: 'Ratih Kumala', 
    price: 78000, 
    originalPrice: 98000,
    category: 'Romance', 
    tags: ['Novel', 'Romance', 'Sejarah'],
    image: 'https://placehold.co/400x600/F3E5F5/8E24AA?text=Gadis+Kretek',
    rating: 4.6,
    reviews: 720,
    discount: 20
  },
  { 
    id: 15, 
    title: 'Orang-Orang Biasa', 
    author: 'Andrea Hirata', 
    price: 82000, 
    originalPrice: 105000,
    category: 'Inspiratif', 
    tags: ['Novel', 'Inspiratif', 'Drama'],
    image: 'https://placehold.co/400x600/E0F7FA/00838F?text=Orang+Orang+Biasa',
    rating: 4.5,
    reviews: 450,
    discount: 22
  },
  { 
    id: 16, 
    title: 'Rumah Kaca', 
    author: 'Pramoedya Ananta Toer', 
    price: 108000, 
    originalPrice: 150000,
    category: 'Sejarah', 
    tags: ['Novel', 'Sejarah', 'Politik'],
    image: 'https://placehold.co/400x600/FFF8E1/FFA000?text=Rumah+Kaca',
    rating: 4.8,
    reviews: 780,
    discount: 28
  },
  { 
    id: 17, 
    title: 'Laut Bercerita', 
    author: 'Leila S. Chudori', 
    price: 95000, 
    originalPrice: 120000,
    category: 'Drama', 
    tags: ['Novel', 'Sejarah', 'Politik'],
    image: 'https://placehold.co/400x600/E8F5E9/388E3C?text=Laut+Bercerita',
    rating: 4.9,
    reviews: 1450,
    discount: 21
  },
  { 
    id: 18, 
    title: 'Sang Pemimpi', 
    author: 'Andrea Hirata', 
    price: 87000, 
    originalPrice: 115000,
    category: 'Inspiratif', 
    tags: ['Novel', 'Inspiratif', 'Pendidikan'],
    image: 'https://placehold.co/400x600/E3F2FD/0288D1?text=Sang+Pemimpi',
    rating: 4.7,
    reviews: 980,
    discount: 24
  },
  { 
    id: 19, 
    title: 'Supernova: Ksatria, Puteri, dan Bintang Jatuh', 
    author: 'Dee Lestari', 
    price: 99000, 
    originalPrice: 130000,
    category: 'Fiksi Ilmiah', 
    tags: ['Novel', 'Sci-Fi', 'Romance'],
    image: 'https://placehold.co/400x600/EDE7F6/5E35B1?text=Supernova',
    rating: 4.8,
    reviews: 1120,
    discount: 24
  },
  { 
    id: 20, 
    title: 'Ayat-Ayat Cinta', 
    author: 'Habiburrahman El Shirazy', 
    price: 76000, 
    originalPrice: 95000,
    category: 'Religi', 
    tags: ['Novel', 'Religi', 'Romance'],
    image: 'https://placehold.co/400x600/FFF3E0/FF6F00?text=Ayat+Ayat+Cinta',
    rating: 4.6,
    reviews: 1580,
    discount: 20
  }
];
export const stationery = [
  { id: 101, title: 'Buku Tulis Premium A5', brand: 'Sidu', price: 15000, category: 'Kertas', image: 'https://placehold.co/400x400?text=Buku+Tulis' },
  { id: 102, title: 'Pulpen Gel 0.5mm (Set 12)', brand: 'Faster', price: 45000, category: 'Alat Tulis', image: 'https://placehold.co/400x400?text=Pulpen' },
  { id: 103, title: 'Correction Tape', brand: 'Kenko', price: 12000, category: 'Koreksi', image: 'https://placehold.co/400x400?text=Correction' },
  { id: 104, title: 'Stapler Heavy Duty', brand: 'Max', price: 65000, category: 'Perlengkapan', image: 'https://placehold.co/400x400?text=Stapler' },
  { id: 105, title: 'Sticky Notes Warna-warni', brand: 'Post-it', price: 25000, category: 'Kertas', image: 'https://placehold.co/400x400?text=Sticky+Notes' },
  { id: 106, title: 'Gunting Stainless', brand: 'Joyko', price: 18000, category: 'Alat Potong', image: 'https://placehold.co/400x400?text=Gunting' },
  { id: 107, title: 'Highlighter Set (6 Warna)', brand: 'Stabilo', price: 55000, category: 'Marker', image: 'https://placehold.co/400x400?text=Highlighter' },
  { id: 108, title: 'Binder Clip (Set 20)', brand: 'Kenko', price: 8000, category: 'Organizer', image: 'https://placehold.co/400x400?text=Clips' },
  { id: 109, title: 'Map Kertas L-Folder', brand: 'Bantex', price: 3500, category: 'Organizer', image: 'https://placehold.co/400x400?text=Folder' },
  { id: 110, title: 'Kalkulator Ilmiah', brand: 'Casio', price: 185000, category: 'Elektronik', image: 'https://placehold.co/400x400?text=Kalkulator' },
];
export const testimonials = [
  {
    name: 'Budi Santoso',
    role: 'Mahasiswa',
    text: 'Belanja buku di Nalar sangat mudah dan cepat. Pengiriman tepat waktu dan pelayanan sangat memuaskan!',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?img=12'
  },
  {
    name: 'Siti Rahma',
    role: 'Guru',
    text: 'Koleksi bukunya lengkap dan harganya terjangkau. Sudah langganan di sini untuk kebutuhan mengajar.',
    rating: 5,
    avatar: 'https://i.pravatar.cc/150?img=45'
  },
  {
    name: 'Ahmad Rizki',
    role: 'Penggemar Buku',
    text: 'Tempatnya nyaman untuk cari buku-buku Indonesia. Rekomendasi bukunya juga selalu pas!',
    rating: 4,
    avatar: 'https://i.pravatar.cc/150?img=33'
  }
];
export const dummyTransactions = [];
export const formatCurrency = (amount) => {
  return new Intl.NumberFormat('id-ID', { 
    style: 'currency', 
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(amount);
};